### ISSUE TITLE
河北.js 没有显示

### ISSUE THREAD

**Issue by chfw** [chfw/jupyter-echarts#4]
<img width="303" alt="screen shot 2017-09-27 at 20 40 21" src="https://user-images.githubusercontent.com/4280312/30934030-2e3e4c1e-a3c4-11e7-82ff-29d4346afa82.png">

**Comment by chfw** [comment]
![image](https://user-images.githubusercontent.com/4280312/30956276-b07bb198-a42e-11e7-8c28-9d4bd752b83e.png)

**Comment by chenjiandongx** [comment]
@chfw 
![image](https://user-images.githubusercontent.com/19553554/30956170-f2f87a6c-a468-11e7-9986-39aa393a6924.png)
不是地图本身的问题，我刚排查了一下。是你的 registry.json 里面河北对应的拼音写错了。
![image](https://user-images.githubusercontent.com/19553554/30956234-3a63fb88-a469-11e7-8f80-6acdd062c178.png)
你把 **hebei** 对应写成了 **hubei**，但是图本身没有 **hubei** 依赖的 js 文件，所以导致不能正常显示。

**Comment by chenjiandongx** [comment]
同时阿 @chfw 😄

**Comment by chfw** [comment]
同时同时

**Comment by chenjiandongx** [comment]
那我就不提交更改了，你那边修改就可以了 👍

**Comment by chfw** [comment]
还需要一个晚上再改改

**Comment by chenjiandongx** [comment]
还需要修改什么吗 是地图部分吗？

**Comment by chfw** [comment]
不是地图，是development scripts

**Comment by chfw** [comment]
你可以i先release pycharts.
